services:
  - type: web
    name: scraper-compras-paraguai
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PIP_NO_CACHE_DIR
        value: "1"
    disk:
      name: scraper-disk
      mountPath: /opt/render/project/src/data
      sizeGB: 1